//! SIP Dialog and session tracking for active calls.

use uuid::Uuid;

/// Represents an active SIP dialog (for either an incoming or outgoing call).
#[derive(Debug, Clone)]
pub struct SipDialog {
    /// SIP Call-ID header.
    pub call_id: String,
    /// Local tag (generated by rustline).
    pub local_tag: String,
    /// Remote tag (generated by the remote party/Asterisk).
    pub remote_tag: Option<String>,
    /// Remote SIP URI or target extension.
    pub remote_uri: String,
    /// Display name of the caller (if available).
    pub remote_name: Option<String>,
    /// Our current local CSeq counter.
    pub local_cseq: u32,
    /// Remote party's last seen CSeq.
    pub remote_cseq: u32,
    /// Stored Via header from the incoming INVITE (needed for replies).
    pub incoming_via: Option<String>,
    /// Stored From header from the incoming INVITE.
    pub incoming_from: Option<String>,
    /// Stored To header from the incoming INVITE.
    pub incoming_to: Option<String>,
    /// True if this call was received from Asterisk (inbound).
    pub is_inbound: bool,
}

impl SipDialog {
    /// Create a new outgoing dialog targeting `target`.
    pub fn new_outbound(target: &str, local_ip: &str) -> Self {
        let call_id = format!("{}@{}", Uuid::new_v4(), local_ip);
        let local_tag = format!("{:x}", rand_u32());
        Self {
            call_id,
            local_tag,
            remote_tag: None,
            remote_uri: target.to_string(),
            remote_name: None,
            local_cseq: 100,
            remote_cseq: 0,
            incoming_via: None,
            incoming_from: None,
            incoming_to: None,
            is_inbound: false,
        }
    }

    /// Create a dialog from an incoming INVITE.
    #[allow(clippy::too_many_arguments)]
    pub fn new_inbound(
        call_id: String,
        remote_uri: String,
        remote_name: Option<String>,
        remote_tag: Option<String>,
        remote_cseq: u32,
        via: String,
        from: String,
        to: String,
    ) -> Self {
        let local_tag = format!("{:x}", rand_u32());
        Self {
            call_id,
            local_tag,
            remote_tag,
            remote_uri,
            remote_name,
            local_cseq: 1,
            remote_cseq,
            incoming_via: Some(via),
            incoming_from: Some(from),
            incoming_to: Some(to),
            is_inbound: true,
        }
    }
}

/// Helper to generate a random 32-bit unsigned integer using uuid.
pub fn rand_u32() -> u32 {
    let bytes = *Uuid::new_v4().as_bytes();
    u32::from_le_bytes([bytes[0], bytes[1], bytes[2], bytes[3]])
}

/// Generate a basic SDP body for PCMA/PCMU audio on a local RTP port.
pub fn build_sdp(local_ip: &str, rtp_port: u16) -> String {
    format!(
        "v=0\r\n\
        o=- 1000 1000 IN IP4 {local_ip}\r\n\
        s=rustline\r\n\
        c=IN IP4 {local_ip}\r\n\
        t=0 0\r\n\
        m=audio {rtp_port} RTP/AVP 8 0 101\r\n\
        a=rtpmap:8 PCMA/8000\r\n\
        a=rtpmap:0 PCMU/8000\r\n\
        a=rtpmap:101 telephone-event/8000\r\n\
        a=fmtp:101 0-16\r\n\
        a=sendrecv\r\n"
    )
}
